services:
  - type: web
    name: security-app
    env: python
    buildCommand: |
      apt-get update && apt-get install -y \
        build-essential \
        cmake \
        pkg-config \
        libx11-dev \
        libatlas-base-dev \
        libgtk-3-dev \
        libboost-python-dev \
        python3-dev \
        && pip install -r requirements.txt
    startCommand: gunicorn web.app:app --worker-class eventlet -w 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: FLASK_APP
        value: web.app
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: security-db
          property: connectionString
    plan: free
    healthCheckPath: /health
    autoDeploy: true

databases:
  - name: security-db
    databaseName: security
    user: security_user
    plan: free 