services:
  - type: web
    name: security-dashboard
    env: python
    buildCommand: |
      apt-get update && apt-get install -y \
        build-essential \
        cmake \
        pkg-config \
        libx11-dev \
        libatlas-base-dev \
        libgtk-3-dev \
        libboost-python-dev \
        python3-dev \
        python3-pip \
        && pip install --upgrade pip \
        && pip install -r requirements.txt
    startCommand: gunicorn web.app:app --worker-class eventlet -w 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: web.app
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /
    autoDeploy: true 